<?php
 return array (
  'email_whitelist_enable' => '0',
  'email_whitelist_suffix' => 
  array (
    0 => 'gmail.com',
    1 => 'qq.com',
    2 => '163.com',
    3 => 'yahoo.com',
    4 => 'sina.com',
    5 => '126.com',
    6 => 'outlook.com',
    7 => 'yeah.net',
    8 => 'foxmail.com',
  ),
  'email_gmail_limit_enable' => '0',
  'recaptcha_enable' => '0',
  'recaptcha_key' => NULL,
  'recaptcha_site_key' => NULL,
  'email_verify' => '0',
  'safe_mode_enable' => '0',
  'register_limit_by_ip_enable' => '0',
  'register_limit_count' => '3',
  'register_limit_expire' => '60',
  'secure_path' => 'admintest',
  'password_limit_enable' => '1',
  'password_limit_count' => '5',
  'password_limit_expire' => '60',
  'email_template' => 'default',
  'email_host' => 'smtp.gmail.com',
  'email_port' => '587',
  'email_username' => 'mortarcloud@gmail.com',
  'email_password' => 'vesvwzqzkirgymjd',
  'email_encryption' => 'tls',
  'email_from_address' => 'mortarcloud@gmail.com',
  'logo' => 'https://i.imgur.com/bxrlKFs.png',
  'force_https' => '0',
  'stop_register' => '0',
  'app_name' => '4G SPEED',
  'app_description' => 'Free data vpn 4G SPEED',
  'app_url' => 'https://4gspeed.me',
  'subscribe_url' => NULL,
  'try_out_plan_id' => '0',
  'try_out_hour' => '1',
  'tos_url' => NULL,
  'currency' => 'vnd',
  'currency_symbol' => 'đ',
) ;